# Generated by Django 5.2.16 on 2026-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Total GST %, split evenly as CGST + SGST', max_digits=4),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
